# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://duyminh2420.github.io/nbdev_demo/"

git_url = "https://github.com/duyminh2420/nbdev_demo/tree/master/"

def custom_doc_links(name): return None
